### ISSUE TITLE
好像无法初始化settings，macos qqnt

### ISSUE THREAD

**Issue by zyzdai** [lclichen/LiteLoaderQQNT-TTS#7]
settings {host: 'https://artrajz-vits-simple-api.hf.space/voice/vits', host_type: 'vits'}
[text_to_speech] 转换文本： 123 到(语言)： 中文
{host: 'https://artrajz-vits-simple-api.hf.space/voice/vits', host_type: 'vits'}
[text_to_speech] [转换出错] TypeError: Cannot read properties of undefined (reading 'vits')
    at call_tts (local:////Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/text_to_speech/src/renderer.js:12:50)
    at HTMLDivElement.<anonymous> (local:////Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/text_to_speech/src/renderer.js:90:30)
​ Uncaught TypeError: Cannot read properties of undefined (reading 'vits')
    at HTMLDivElement.<anonymous> (local:////Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/text_to_speech/src/renderer.js:91:84)

**Comment by lclichen** [comment]
啊什么情况（没有iOS设备的我有点茫然😦

**Comment by zyzdai** [comment]
> 啊什么情况（没有iOS设备的我有点茫然😦

An error occurred while converting /Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/text_to_speech/tts.wav to .wav. Details: /bin/sh: ffmpeg: command not found

**Comment by zyzdai** [comment]
> 啊什么情况（没有iOS设备的我有点茫然😦

之前的问题解决了。现在macos 出现无法使用ffmpeg,终端是可以正常执行的
